version: '2.0'
services:
  python:
    image: python:3.7
    working_dir: /code
    volumes:
    - .:/code
  aws:
    image: mesosphere/aws-cli:1.14.5
    entrypoint: sh
    env_file: .env
    working_dir: /code
    volumes:
    - .:/code