version: '2.0'
services:
  python:
    image: python:3.7
    working_dir: /code
    volumes:
    - .:/code
  aws:
    image: mesosphere/aws-cli:1.14.5
    entrypoint: sh
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    working_dir: /code
    volumes:
    - .:/code