name: Builder
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Package
        run: make package
      - name: Save artifact to GitHub 
        uses: actions/upload-artifact@v2-preview
        with:
          name: code
          path: output/code.zip
      - name: Publish AWS S3
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        run: make publish
